### ISSUE TITLE
missing data file

### ISSUE THREAD

**Issue by john-livingston** [jpdeleon/tql#2]
```
(py3) jhl@13x:~/github/tql$ make_tql -toi 867.01
Created TAP+ (v1.0.1) - Connection:
        Host: gea.esac.esa.int
        Use HTTPS: False
        Port: 80
        SSL Port: 443
WARNING: W35: None:5:0: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W35: None:6:0: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W35: None:7:0: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W35: None:8:0: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W35: None:10:0: W35: 'value' attribute required for INFO elements [astropy.io.votable.tree]
WARNING: W27: None:11:0: W27: COOSYS deprecated in VOTable 1.2 [astropy.io.votable.tree]
WARNING: W06: None:48:0: W06: Invalid UCD 'arith.ratio': Secondary word 'arith.ratio' is not valid as a primary word [astropy.io.votable.tree]
WARNING: W50: None:51:0: W50: Invalid unit string 'mas.yr**-1' [astropy.io.votable.tree]
WARNING: W50: None:54:0: W50: Invalid unit string 'mas.yr**-1' [astropy.io.votable.tree]
WARNING: W50: None:57:0: W50: Invalid unit string 'mas.yr**-1' [astropy.io.votable.tree]
WARNING: W50: None:60:0: W50: Invalid unit string 'mas.yr**-1' [astropy.io.votable.tree]
WARNING: W50: None:123:0: W50: Invalid unit string 'mas**-2' [astropy.io.votable.tree]
WARNING: W50: None:126:0: W50: Invalid unit string 'um**-1' [astropy.io.votable.tree]
WARNING: W06: None:129:0: W06: Invalid UCD 'em.wavenumber;stat.error': Primary word 'stat.error' is not valid as a secondary word [astropy.io.votable.tree]
WARNING: W50: None:129:0: W50: Invalid unit string 'um**-1' [astropy.io.votable.tree]
WARNING: W06: None:141:0: W06: Invalid UCD 'pos.errorEllipse;stat.max': Secondary word 'pos.errorEllipse' is not valid as a primary word [astropy.io.votable.tree]
WARNING: W50: None:156:0: W50: Invalid unit string ''electron'.s**-1' [astropy.io.votable.tree]
WARNING: W50: None:159:0: W50: Invalid unit string ''electron'.s**-1' [astropy.io.votable.tree]
WARNING: W06: None:162:0: W06: Invalid UCD 'arith.ratio': Secondary word 'arith.ratio' is not valid as a primary word [astropy.io.votable.tree]
WARNING: W50: None:171:0: W50: Invalid unit string ''electron'.s**-1' (suppressing further warnings of this type...) [astropy.io.votable.tree]
WARNING: W06: None:177:0: W06: Invalid UCD 'arith.ratio': Secondary word 'arith.ratio' is not valid as a primary word [astropy.io.votable.tree]
WARNING: W06: None:192:0: W06: Invalid UCD 'arith.ratio': Secondary word 'arith.ratio' is not valid as a primary word [astropy.io.votable.tree]
WARNING: W06: None:204:0: W06: Invalid UCD 'phot.color': Unknown word 'phot.color' [astropy.io.votable.tree]
WARNING: W06: None:207:0: W06: Invalid UCD 'phot.color': Unknown word 'phot.color' [astropy.io.votable.tree]
WARNING: W06: None:210:0: W06: Invalid UCD 'phot.color': Unknown word 'phot.color' [astropy.io.votable.tree]
WARNING: W06: None:282:0: W06: Invalid UCD 'phys.size.radius;stat.error': Primary word 'stat.error' is not valid as a secondary word (suppressing further warnings of this type...) [astropy.io.votable.tree]
Traceback (most recent call last):
  File "/home/jhl/miniconda3/envs/py3/bin/make_tql", line 4, in <module>
    __import__('pkg_resources').run_script('tql==0.1.1', 'make_tql')
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1460, in run_script
    exec(script_code, namespace, namespace)
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/tql-0.1.1-py3.7.egg/EGG-INFO/scripts/make_tql", line 180, in <module>
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/tql-0.1.1-py3.7.egg/tql/tql.py", line 2970, in plot_target_in_cluster
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/tql-0.1.1-py3.7.egg/tql/tql.py", line 2913, in get_cluster_members_near_target
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/tql-0.1.1-py3.7.egg/tql/tql.py", line 2879, in get_cluster_near_target
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/tql-0.1.1-py3.7.egg/tql/tql.py", line 2844, in combine_open_clusters_near_far
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/tql-0.1.1-py3.7.egg/tql/tql.py", line 2819, in get_open_clusters_near
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/jhl/miniconda3/envs/py3/lib/python3.7/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'../data/TablesGaiaDR2HRDpaper/Table3_Mean parameters for 9 open clusters within 250pc.tsv' does not exist: b'../data/TablesGaiaDR2HRDpaper/Table3_Mean parameters for 9 open clusters within 250pc.tsv'
```

**Comment by jpdeleon** [comment]
Fixed.
